import { AxiosError, AxiosRequestConfig } from "axios";
import { z } from "zod";
import { axiosInstance } from "./axios";

// Type for the mutator function that orval expects for react-query
export type MutatorRequestOptions = {
  url: string;
  method: "GET" | "POST" | "PUT" | "DELETE" | "PATCH" | "HEAD" | "OPTIONS";
  params?: Record<string, unknown>;
  data?: unknown;
  headers?: Record<string, string>;
  responseType?: "json" | "blob" | "text" | "arraybuffer";
  signal?: AbortSignal;
};

/**
 * Custom mutator function for orval that validates requests and responses using zod schemas.
 *
 * This mutator is used by orval's generated react-query hooks. To use zod validation:
 * 1. Import the zod schemas generated by orval (from src/generated/api/schemas)
 * 2. Create a schema map or use endpoint-specific validation
 * 3. Validate request/response data using the schemas
 *
 * Example usage with zod schemas:
 * ```typescript
 * import { SomeRequestSchema, SomeResponseSchema } from '@generated/api/schemas';
 *
 * // In the mutator, validate based on endpoint or config
 * if (config.url.includes('/some-endpoint')) {
 *   SomeRequestSchema.parse(config.data);
 *   const response = await axiosInstance(config);
 *   return SomeResponseSchema.parse(response.data);
 * }
 * ```
 *
 * @param config - The request configuration from orval
 * @returns The response data (for react-query, this should be just the data, not the full response)
 */
export async function customInstance<TData = unknown>(
  config: MutatorRequestOptions
): Promise<TData> {
  try {
    // Prepare axios config
    const axiosConfig: AxiosRequestConfig = {
      url: config.url,
      method: config.method,
      params: config.params,
      data: config.data,
      headers: config.headers,
      responseType: config.responseType || "json",
      signal: config.signal,
    };

    // Make the request
    const response = await axiosInstance.request<TData>(axiosConfig);

    // TODO: Add zod validation here based on endpoint
    // Example:
    // const zodSchema = getZodSchemaForEndpoint(config.url);
    // if (zodSchema) {
    //   return zodSchema.parse(response.data);
    // }

    // Return just the data (react-query expects this)
    return response.data;
  } catch (error) {
    // Handle validation errors
    if (error instanceof z.ZodError) {
      const validationError = new Error(
        `Validation error: ${error.issues.map((e) => `${e.path.join(".")}: ${e.message}`).join(", ")}`
      );
      (validationError as any).zodError = error;
      throw validationError;
    }

    // Handle axios errors
    if (error instanceof AxiosError) {
      const axiosError = error.response
        ? {
            status: error.response.status,
            statusText: error.response.statusText,
            data: error.response.data,
            headers: error.response.headers,
          }
        : {
            message: error.message,
            code: error.code,
          };
      throw axiosError;
    }

    // Re-throw other errors
    throw error;
  }
}

// Export default for orval
export default customInstance;
